name: Build and push image

on:
  push:
    tags:
      - '*-*'

jobs:
  build-image:
    name: Build and push multi arch image
    runs-on: ubuntu-latest
    steps:

      # --- Container setup --- 

      - name: Checkout
        uses: actions/checkout@v3

      # Gets name of the triggering tag.
      # Tag name must equal a folder name containing a make file. E.g. 11.0.16-5.2022.3
      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      # --- Working steps ---

      - name: Build image
        run: |
          cd ${{ env.TAG_NAME }} 
          make latest